.\" Copyright 2018 Sam McSweeney (sammy.mcsweeney@gmail.com)
.TH LIGHT_CYLINDER 3 2018-02-22 "" "Pulsar Geometry"
.SH NAME
light_cylinder \- calculate the light cylinder radius
.SH SYNOPSIS
.nf
.B #include <psrgeom.h>
.PP
.BI "double light_cylinder(double " P ");"
.fi
.PP
.SH DESCRIPTION
The
.BR light_cylinder ()
function calculates the light cylinder radius for a pulsar with period
.IR P"."
.SH RETURN VALUE
The
.BR light_cylinder ()
function returns the value of the light cylinder radius.
.SH EXAMPLE
.EX
#include <psrgeom.h>

int main(int argc, char *argv[])
{
    double P  = 1.0;
    double rL = light_cylinder( P );

    exit(EXIT_SUCCESS);
}
.EE
.SH SEE ALSO
.BR psrgeom (3),
