.\" Copyright 2017 Sam McSweeney (sammy.mcsweeney@gmail.com)
.TH POSANGLE_TO_BEAMANGLE 3 2018-03-10 "" "Pulsar Geometry"
.SH NAME
posangle_to_beamangle \- converts position angle to beam opening angle in a dipole magnetic field
.SH SYNOPSIS
.nf
.B #include <psrgeom.h>
.PP
.BI "void posangle_to_beamangle(psr_angle *" pa ", psr_angle *" ba ");"
.fi
.PP
.SH DESCRIPTION
The
.BR posangle_to_beamangle ()
function converts the position angle
.I ba
to a beam opening angle
.IR pa .
.EX


    Z
    |
    |
    |            .  o     .
    X      .                  .
    |   .                       .
    | .                          .
    |.                           .
    Y-------------------------------------> x
 

.EE
In the figure, "o" is a point on the dipole field line, denoted with dots
("."), "X" is the point on the z-axis where the tangent line of "o"
intersects it, Y is at the origin, and Z is a point higher up on the
z-axis. Then we have the definitions
.I pa
= angle(oYZ) and
.I ba
= angle(oXZ).
.SH RETURN VALUE
The
.BR posangle_to_beamangle ()
function does not return any value.
.SH SEE ALSO
.BR beamangle_to_posangle (3)
