.\" Copyright 2017 Sam McSweeney (sammy.mcsweeney@gmail.com)
.TH SET_ANGLE_COS 3 2017-12-19 "" "Pulsar Geometry"
.SH NAME
set_angle_cos \- set the values of an "angle" struct
.SH SYNOPSIS
.nf
.B #include <psrgeom.h>
.PP
.BI "void set_angle_cos(angle *" ang ", double " Cos ");"
.fi
.PP
.SH DESCRIPTION
The
.BR set_angle_cos ()
function sets the member values of \fIang\fP to the values corresponding
to the angle whose cosine is \fICos\fP. Specifically, the equivalent angle in
radians, the equivalent angle in degrees, and the sine of the angle are
calculated and stored in the \fIang\fP.

\fICos\fP can be any value that is a valid input to the
.BR acos ()
function in
.BR math.h.
First the radians value is set to the output of
.BR acos (),
and then the degrees and sine values are calculated from the radians
value in the same way as
.BR set_angle_rad ().
.SH RETURN VALUE
The
.BR set_angle_cos ()
function does not return any value.
.SH EXAMPLE
.EX
#include <psrgeom.h>

int main(int argc, char *argv[])
{
    angle *a = create_angle();

    set_angle_cos( 0.0 );

    /* Now,
       a->rad = PI,
       a->deg = 90.0,
       a->sin = 1.0,
       a->cos = 0.0
    */

    exit(EXIT_SUCCESS);
}
.EE
.SH SEE ALSO
.BR create_angle (3),
.BR create_angle_rad (3),
.BR create_angle_deg (3),
.BR copy_angle (3),
.BR destroy_angle (3),
.BR set_angle_rad (3),
.BR set_angle_deg (3),
.BR set_angle_sin (3)
